### ISSUE TITLE
Issue invoices and download as PDF

### ISSUE THREAD

**Issue by deepakchandra00** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#1]
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-09-05 17:02:38 --> Severity: Core Warning --> PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory Unknown 0
ERROR - 2019-09-05 17:02:39 --> Severity: Core Warning --> PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory Unknown 0
ERROR - 2019-09-05 17:02:39 --> 404 Page Not Found: /index
ERROR - 2019-09-05 17:02:39 --> Severity: Core Warning --> PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory Unknown 0
ERROR - 2019-09-05 17:02:41 --> Generating PDF failed. See logs for more information. Problem for user - Array
(
    [email] => deepak@gmail.com
    [type] => 1
)

ERROR - 2019-09-05 17:02:41 --> Severity: Warning --> file_get_contents(/tmp/html_pdfyg950E): failed to open stream: No such file or directory /home/deepakchandra/public_html/mvtsindia.com/insurance/application/libraries/HtmlToPdf.php 95
ERROR - 2019-09-05 17:02:41 --> Couldn't read the PDF file for user - Array
(
    [email] => deepak@gmail.com
    [type] => 1
)

ERROR - 2019-09-05 17:02:41 --> Severity: Core Warning --> PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory Unknown 0

kindly check this.. thanks

**Comment by kirilkirkov** [comment]
@deepakchandra00 Maybe the problem is in yours cpanel hosting - tmp directory

**Comment by deepakchandra00** [comment]
The switch --footer-html, is not support using unpatched qt, and will be ignored.wkhtmltopdf: cannot connect to X server 

i have got this error also.

**Comment by kirilkirkov** [comment]
this is because you use cpanel. Install the application on vps and install wkhtmltopdf

**Comment by deepakchandra00** [comment]
can u guide me how to install Thanks.

**Comment by deepakchandra00** [comment]
Thanks i have install this. here is process

https://gist.github.com/isogram/1b39fa91f34e35e66c84fe066cc37577
