### ISSUE TITLE
Remove subscription plan 

### ISSUE THREAD

**Issue by ugintl** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#10]
I want to remove subscription functionality completely. How to do it?

**Comment by kirilkirkov** [comment]
Hello @ugintl 
you will need to make code changes to remove it. 
It will easy for you if you add to the database big number for the limits.

**Comment by kirilkirkov** [comment]
Insert you custom plan in the custom plans table
This will work for you
