### ISSUE TITLE
there is no file loadlanguage/all.js

### ISSUE THREAD

**Issue by lanryryan** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#12]
Hi author,

I can visit the invoice system now, but I can not add an item when I clicked button "add item". And found that the system response file "loadlanguage/all.js" no found.
![image](https://github.com/kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System/assets/10055405/38a52bbb-b5b6-49b2-8ef7-41a5c996ed3e)

How should I fix this issue?

Best Regards

**Comment by kirilkirkov** [comment]
Hey @lanryryan 
I have uploaded a fix - https://github.com/kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System/commit/a508b6f58198d37a43161102ed2a03e108241d61

Can you update your code and try again?

About the loadlanguage url, are you sure that your server reads the .htaccess file?
