### ISSUE TITLE
Need admin and user id and password

### ISSUE THREAD

**Issue by Cyberfolks** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#2]
hi @kirilkirkov hope you are doing well.
i want to work on it but in readme file here is no id pass for admin panel as user and admin.

**Comment by kirilkirkov** [comment]
@Cyberfolks 
I think you can login in administration with /admin
username: admin
password: admin

You can use online version if you want - https://pminvoice.com/

**Comment by kirilkirkov** [comment]
Or just reset your password from the database

**Comment by Cyberfolks** [comment]
thank you for very quick reply... 
/admin is not working on your provided link.
even i installed it on https://cyberfolks.website/invoice/ and cant login from front page and inside admin here are no settings for changing password or adding useres.

**Comment by kirilkirkov** [comment]
@Cyberfolks 
Open https://cyberfolks.website/invoice/admin and then enter 
admin
admin

:) Its work. I test it on your side

**Comment by Cyberfolks** [comment]
@kirilkirkov thank you brother just added now user and now its working fine.

now i just want to know why pdf are not generating. i asked my hosting provider to add that library (you provided other issue) but they denied. is there any other option to download and send in mail.

**Comment by kirilkirkov** [comment]
@Cyberfolks  You need to use VPS hosting to install the library that generate pdf files. Most of shared hostings have restrictions. There is no option for this platform to generate pdf files without third party library

**Comment by ugintl** [comment]
@Cyberfolks When I login as admin at http://example.com/admin I see below page. Do you also see like this?
![admin](https://user-images.githubusercontent.com/12570802/133628997-f8b8ec4c-f469-4cf5-8bf4-7503c9bf28f8.jpeg)
@kirilkirkov
