### ISSUE TITLE
issues:HTTP ERROR 500

### ISSUE THREAD

**Issue by Louisstree** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#3]
hi,kirilkirkov
im follow https://github.com/kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#installation-in-3-easy-steps

HTTP ERROR 500
Centos  7.7
Apache 2.4.41
Mysql 5.7.29
Php7.2

could you hlep me .
This project is really great.

**Comment by kirilkirkov** [comment]
@Louisstree 
Change ENVIRONMENT in index.php file to development and tell me what error you see?
