### ISSUE TITLE
index page error

### ISSUE THREAD

**Issue by esmm90** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#4]
Hey! I've a nice problem deploying this beatiful system you create; when I access via browser it looks like this
![image](https://user-images.githubusercontent.com/50113003/80009626-b506a700-849f-11ea-8e18-1ec3c88dc3cd.png)

The deploy runs under:
CentOS 8
Apache 2.4
MariaDB 10.3
PHP 7.4.5

**Comment by AbdelmalekDJ** [comment]
> Hey! I've a nice problem deploying this beatiful system you create; when I access via browser it looks like this
> ![image](https://user-images.githubusercontent.com/50113003/80009626-b506a700-849f-11ea-8e18-1ec3c88dc3cd.png)
> 
> The deploy runs under:
> CentOS 8
> Apache 2.4
> MariaDB 10.3
> PHP 7.4.5

Hello Bro, Can you please tell me how did you solve this issue ? :(

**Comment by kirilkirkov** [comment]
https://github.com/kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System/blob/master/application/config/config.php
Change your base_url in configuration
