### ISSUE TITLE
controller files are missing 

### ISSUE THREAD

**Issue by ghost** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#5]
i notice that controller files are missing. i can see only 3 controllers please review and update the code.
thanks!

**Comment by kirilkirkov** [comment]
Nothing is missing :). Another controllers are in the modules directory.
@iamomerbhutta

**Comment by ghost** [comment]
oh got it. actually the issue was with "index.php". so when i tried to login it redirect me to the error page. then i test with index.php and it works. thanks!
