### ISSUE TITLE
Css not loading and cannot login

### ISSUE THREAD

**Issue by AbdelmalekDJ** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#6]
hello @kirilkirkov i hope you doing fine, first thank you for the great work you did in this project.
I just wanted some help with this 
![image](https://user-images.githubusercontent.com/68859539/88587837-7fe59400-d04e-11ea-9217-215e970660d5.png)

And can you please tell me the reason so i can learn it

**Comment by kirilkirkov** [comment]
@AbdelmalekDJ Did you change the base url in system configuration with yours domain?

https://github.com/kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System/blob/master/application/config/config.php

**Comment by AbdelmalekDJ** [comment]
@kirilkirkov yes bro, i have to changed to my domain and try changing different URLs who are enabled in hosts in windows folder

I tried multiple things but i think it's hard for me to find solution alone

**Comment by kirilkirkov** [comment]
@AbdelmalekDJ  Are you sure that yours .htaccess file works ?

**Comment by AbdelmalekDJ** [comment]
@kirilkirkov i didn't touch anything on .htaccess file it's like this 👍 RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
<IfModule mod_headers.c>    
    Header set Access-Control-Allow-Origin *
</IfModule>

**Comment by kirilkirkov** [comment]
@AbdelmalekDJ 
Something in yours server configuration not works. Are you sure that you have enabled module rewrite for apache - https://httpd.apache.org/docs/current/mod/mod_rewrite.html and also have AllowOverride All in your vhost?
I now  tested the platform and it works.
