### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Romukas** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#7]
Hi, what is the license of this project? Can you add a license file? Thanks.

**Comment by kirilkirkov** [comment]
@Romukas Hi, For what a type of usage you want to download it?

**Comment by Romukas** [comment]
I am looking to make software (I would sell) for a logistics warehouse and, at first glance, yours looks suitable to add additional functionality upon. But before getting invested, I am trying to find out if I can legally do that (I would publicly share my changes of course, if your license requires it).

**Comment by kirilkirkov** [comment]
Write me to kirilkirkov91@gmail.com if you want to resell it
