### ISSUE TITLE
Add Item button not working in invoice

### ISSUE THREAD

**Issue by github-saurav** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#8]
https://user-images.githubusercontent.com/68456364/125493045-f652c893-c3c2-4755-99ec-b189b750126f.png

**Comment by github-saurav** [comment]
> https://user-images.githubusercontent.com/68456364/125493045-f652c893-c3c2-4755-99ec-b189b750126f.png

**Comment by kirilkirkov** [comment]
@github-saurav 
Make sure that you application is in Production mode.
Open the index.php file from main directory and set ENVIRONMENT constant to "production"

**Comment by sapomuyverde** [comment]
Hi,
Same situation here, I already verified the constant in the index.php file and it is already in production mode.

![img1](https://user-images.githubusercontent.com/15135396/133358704-8d110798-1f93-4fcc-9f3f-c55a97573cb0.png)

any other tips?

**Comment by sapomuyverde** [comment]
Hi,

Any help with that problem?.

Regards,
Javier

**Comment by PaLiNYG96** [comment]
To fix the above issue, go to /application/modules/users/views/invoices/newinvoice.php 
Change Line 244 to: 
`$thisDir = ltrim(str_replace(getcwd(), '', dirname(__FILE__)), '\\');`
