### ISSUE TITLE
Admin dashboard missing

### ISSUE THREAD

**Issue by ugintl** [kirilkirkov/Electronic-Invoicing-And-Warehouse-Management-System#9]
When I login as admin at http://example.com/admin I see the admin page like this. Is it an error or deliberate?

![admin](https://user-images.githubusercontent.com/12570802/133630307-04e04931-b94c-4eb5-b1d9-0fa79851fffc.jpeg)

**Comment by ugintl** [comment]
If this is the admin dashboard, then I would like to remove it completely or disable temporarily.

**Comment by kirilkirkov** [comment]
@ugintl 
Yes this is.
remove it from the config.php
